name: Environment Secrets Demo

on: workflow_dispatch

jobs:
  deployment:
    runs-on: ubuntu-latest

    # refer the secrets from environment of production
    environment:
      name: production
      url: "https://github.com"

    steps:
      - name: Print Environment Secrets
        run: echo "env secret is ${{ secrets.PROD_SECRET }}"
