name: Environment Secrets Demo

on: workflow_dispatch

jobs:
  deployment:
    runs-on: ubuntu-latest

    # refer the secrets from environment of PROD_ENV
    environment:
      name: PROD_ENV
      url: https://github.com

    steps:
      - name: Print Environment Secrets
        run: |
          echo "env secret is ${{ secrets:ENV_SECRET_APP }}"
