name: Passing values between Jobs
on: workflow_dispatch

jobs:
  job1:
    runs-on: ubuntu-latest

    # Map a step output to a job output
    outputs:
      output1: ${{ steps.step1.outputs.test }}
      output2: ${{ steps.step2.outputs.test }}

    steps:
      - name: Create step1 test var
        id: step1
        run: echo "::set-output name=test::testValue1"

      - name: Create step2 test var
        id: step2
        run: echo "::set-output name=test::testValue2"

  job2:
    runs-on: ubuntu-latest
    needs: job1
    steps:
      - name: Print vars from Job1 steps
        run: |
          echo "var from Job1 step1 is ${{ needs.job1.outputs.output1 }}"
          echo "var from Job1 step2 is ${{ needs.job1.outputs.output2 }}"
