name: Basic Secrets workflow

on:
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Print secrets as secret
        run: |
          echo "My top secret: ${{ secrets.MY_TOP_SECRET }}"
          echo "secret which is not there: ${{ secrets.I_DONT_EXIST }}"

      - name: assign secret to env and Print
        run: |
          echo "Secret in env: ${{ env.SECRET_AS_ENV }}"
        env:
          SECRET_AS_ENV: ${{ secrets.MY_TOP_SECRET }}
          testvar: value-3
