name: Set Env Vars on fly Demo

on: workflow_dispatch

jobs:
  setEnvVar:
    runs-on: ubuntu-latest

    steps:
      - name: set the value
        id: step_one
        run: |
          echo "action_state=yellow" >> $GITHUB_ENV

      - name: use the value
        id: step_two
        run: echo "Your state is ${{ env.action_state }}"
